services:
  weaviate:
    image: semitechnologies/weaviate:1.28.3
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - RAFT_ENABLE_ONE_NODE_RECOVERY=true
    volumes:
      - weaviate-data:/var/lib/weaviate

  embedding-service:
    build:
      context: ./embedding
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - weaviate
    environment:
      - FLASK_ENV=production
volumes:
  weaviate-data:
