### READERS
POST http://localhost:8080/v1/graphql
Content-Type: application/json

{
  "query": "{ Get { Reader { name readPapers { ... on Paper { id } } } } }"
}

### SCHEMA
GET http://localhost:8080/v1/schema

### PAPERS
GET http://localhost:8080/v1/objects?class=Paper

### READERS
GET http://localhost:8080/v1/objects?class=Reader


### CLEAR
DELETE http://localhost:8080/v1/schema/Paper

### CLEAR
DELETE http://localhost:8080/v1/schema/Reader

### CLEAR
DELETE http://localhost:8080/v1/schema/PaperReference




### PAPERS BY AUTHOR
POST http://localhost:8080/v1/graphql
Content-Type: application/json

{
  "query": "{ Get { Paper { title authors { ... on Reader { name } } } } }"
}



### Get single article (00091759-62dd-4b9c-ab67-66b429d9eb51)
GET http://localhost:8080/v1/objects
Content-Type: application/json

{
  "class": "Paper",
  "limit": 1,
  "where": {
    "path": ["title"],
    "operator": "Equal",
    "valueText": "Filter Bubbles, Echo Chambers, and Online News Consumption"
  }
}


###
POST http://localhost:8080/v1/graphql
Content-Type: application/json

{"query":"{ Get { Paper(nearObject: {id: \"00091759-62dd-4b9c-ab67-66b429d9eb51\"} limit: 100) { title abstract authors { ... on Reader { name } } } } }"}


###
POST http://localhost:8080/v1/schema
Content-Type: application/json

{
  "class": "Paper",
  "properties": [
    {
      "name": "title",
      "dataType": ["text"],
      "tokenization": "whitespace"
    },
    {
      "name": "abstract",
      "dataType": ["text"],
      "tokenization": "whitespace"
    },
    {
      "name": "embedding",
      "dataType": ["number[]"],
      "indexFilterable": true
    },
    {
      "name": "authors",
      "dataType": ["Reader"]
    }
  ],
  "vectorizer": "none",
  "vectorIndexConfig": {
    "distance": "cosine",
    "efConstruction": 128,
    "ef": -1,
    "maxConnections": 32
  }
}
